version: "3.8"
services:
    db:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
        ports:
            - ${DB_PORT}:${DB_PORT}
        container_name: ${DB_PASSWORD}
